### ISSUE TITLE
Enable to build the project

### ISSUE THREAD

**Issue by temala** [dragouf/Ollert#1]
Hi,

thanks for building this asp mvc trello based project. But when I try to build the project multiple errors appears related to typescript 

Erreur  1   Échec inattendu de la tâche "VsTsc".
System.Resources.MissingManifestResourceException: Could not find any resources appropriate for the specified culture or the neutral culture.  Make sure "TypeScript.Tasks.Strings.resources" was correctly embedded or linked into assembly "TypeScript.Tasks" at compile time, or that all the satellite assemblies required are loadable and fully signed.
   at System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(String fileName)
   at System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet(CultureInfo culture, Dictionary`2 localResourceSets, Boolean tryParents, Boolean createIfNotExists, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo requestedCulture, Boolean createIfNotExists, Boolean tryParents, StackCrawlMark& stackMark)
   at System.Resources.ResourceManager.InternalGetResourceSet(CultureInfo culture, Boolean createIfNotExists, Boolean tryParents)
   at System.Resources.ResourceManager.GetString(String name, CultureInfo culture)
   at TypeScript.Tasks.Strings.get_ErrorListBuildPrefix()
   at TypeScript.Tasks.VsTsc.LogEventsFromTextOutput(String singleLine, MessageImportance messageImportance)
   at Microsoft.Build.Utilities.ToolTask.LogMessagesFromStandardErrorOrOutput(Queue dataQueue, ManualResetEvent dataAvailableSignal, MessageImportance messageImportance, StandardOutputOrErrorQueueType queueType)
   at Microsoft.Build.Utilities.ToolTask.HandleToolNotifications(Process proc)
   at Microsoft.Build.Utilities.ToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at TypeScript.Tasks.VsTsc.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands)
   at Microsoft.Build.Utilities.ToolTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__20.MoveNext() Ollert

So please help me with this

**Comment by dragouf** [comment]
To be sure to transpiled with correct version of TypeScript I included TypeScript compiler and added as a msbuild task inside "Ollert.csproj" file.
But it seems you are using french version of Visual Studio and I didn't include french resources of TypeScript. 

Try to rename the folder Tools/TypeScript/1.4/en to "fr" (maybe or "fr-FR" ?) or edit Tools\TypeScript\Microsoft.TypeScript.jsproj.targets and hard code locale code to "en" instead of using locale system variables at line 17 and 19 of the file.

Btw there is a small bug inside the application. It always gets all attachments data from sql server when a "card" is opened. If IIS and SQL are on the same server it's fine but in case they are connected through a slow network it may be a problem. I made a fix that I still didn’t commit. I will as soon as I have time. 
A last thing. If you want to test the project, I recommend you to fork it and create a free AppHarbor application from it.

**Comment by dragouf** [comment]
@temala please tell me if you were able to solved this problem.

**Comment by temala** [comment]
hi, sorry to respond late,  I'll test this soon, thank you for your help.

**Comment by dragouf** [comment]
Ok I wait for your feedback.
